import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar/navbar";
import Footer from "./footer/page";
import { PrimeReactProvider } from 'primereact/api'; 
import "./globals.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import 'primereact/resources/primereact.min.css'; // core css
import 'primeicons/primeicons.css'; // iconos

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airesval",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <PrimeReactProvider>
        <html lang="en">
          <body className="flex flex-col min-h-screen">
            <header className="relative z-10">
              <Navbar/>
            </header>
            {children}
            <Footer/>
            </body>
        </html>
    </PrimeReactProvider>
  );
}
